name: guardian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  url_launcher: ^6.3.1
  location: ^8.0.0
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  sentiment_dart: ^0.0.5
  dart_sentiment: ^0.0.9
  http: ^1.4.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  emoji_picker_flutter: ^1.6.3
  permission_handler: ^10.2.0
  google_speech: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
